# Generated by Django 2.2.3 on 2019-09-06 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses_name',
            old_name='image',
            new_name='pic',
        ),
    ]
