# Generated by Django 2.2.3 on 2019-09-06 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20190906_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses_name',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='courses_name',
            name='pic',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
