# Generated by Django 2.2.3 on 2019-09-06 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_courses_name_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='java_courses',
            name='course_name',
            field=models.CharField(default='java', max_length=100),
        ),
    ]
