# Generated by Django 2.2.3 on 2019-09-09 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_c_courses_django_courses_javascript_courses_laravel_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='c_courses',
            name='ans_op1',
            field=models.CharField(default='false', max_length=100),
        ),
        migrations.AddField(
            model_name='c_courses',
            name='ans_op11',
            field=models.CharField(default='false', max_length=100),
        ),
        migrations.AddField(
            model_name='c_courses',
            name='ans_op2',
            field=models.CharField(default='false', max_length=100),
        ),
        migrations.AddField(
            model_name='c_courses',
            name='ans_op22',
            field=models.CharField(default='false', max_length=100),
        ),
        migrations.AddField(
            model_name='c_courses',
            name='ans_op222',
            field=models.CharField(default='false', max_length=100),
        ),
        migrations.AddField(
            model_name='c_courses',
            name='ans_op2222',
            field=models.CharField(default='false', max_length=100),
        ),
        migrations.AddField(
            model_name='c_courses',
            name='ans_op3',
            field=models.CharField(default='false', max_length=100),
        ),
        migrations.AddField(
            model_name='c_courses',
            name='ans_op33',
            field=models.CharField(default='false', max_length=100),
        ),
        migrations.AddField(
            model_name='c_courses',
            name='ans_op333',
            field=models.CharField(default='false', max_length=100),
        ),
        migrations.AddField(
            model_name='c_courses',
            name='ans_op3333',
            field=models.CharField(default='false', max_length=100),
        ),
        migrations.AddField(
            model_name='c_courses',
            name='ans_op4',
            field=models.CharField(default='false', max_length=100),
        ),
        migrations.AddField(
            model_name='c_courses',
            name='ans_op44',
            field=models.CharField(default='false', max_length=100),
        ),
        migrations.AddField(
            model_name='c_courses',
            name='op1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='c_courses',
            name='op11',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='c_courses',
            name='op2',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='c_courses',
            name='op22',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='c_courses',
            name='op222',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='c_courses',
            name='op2222',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='c_courses',
            name='op3',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='c_courses',
            name='op33',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='c_courses',
            name='op333',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='c_courses',
            name='op3333',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='c_courses',
            name='op4',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='c_courses',
            name='op44',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='c_courses',
            name='qusestion1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='c_courses',
            name='qusestion2',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='c_courses',
            name='qusestion3',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='c_courses',
            name='qusestion4',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='django_courses',
            name='ans_op1',
            field=models.CharField(default='false', max_length=100),
        ),
        migrations.AddField(
            model_name='django_courses',
            name='ans_op11',
            field=models.CharField(default='false', max_length=100),
        ),
        migrations.AddField(
            model_name='django_courses',
            name='ans_op2',
            field=models.CharField(default='false', max_length=100),
        ),
        migrations.AddField(
            model_name='django_courses',
            name='ans_op22',
            field=models.CharField(default='false', max_length=100),
        ),
        migrations.AddField(
            model_name='django_courses',
            name='ans_op222',
            field=models.CharField(default='false', max_length=100),
        ),
        migrations.AddField(
            model_name='django_courses',
            name='ans_op2222',
            field=models.CharField(default='false', max_length=100),
        ),
        migrations.AddField(
            model_name='django_courses',
            name='ans_op3',
            field=models.CharField(default='false', max_length=100),
        ),
        migrations.AddField(
            model_name='django_courses',
            name='ans_op33',
            field=models.CharField(default='false', max_length=100),
        ),
        migrations.AddField(
            model_name='django_courses',
            name='ans_op333',
            field=models.CharField(default='false', max_length=100),
        ),
        migrations.AddField(
            model_name='django_courses',
            name='ans_op3333',
            field=models.CharField(default='false', max_length=100),
        ),
        migrations.AddField(
            model_name='django_courses',
            name='ans_op4',
            field=models.CharField(default='false', max_length=100),
        ),
        migrations.AddField(
            model_name='django_courses',
            name='ans_op44',
            field=models.CharField(default='false', max_length=100),
        ),
        migrations.AddField(
            model_name='django_courses',
            name='op1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='django_courses',
            name='op11',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='django_courses',
            name='op2',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='django_courses',
            name='op22',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='django_courses',
            name='op222',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='django_courses',
            name='op2222',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='django_courses',
            name='op3',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='django_courses',
            name='op33',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='django_courses',
            name='op333',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='django_courses',
            name='op3333',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='django_courses',
            name='op4',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='django_courses',
            name='op44',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='django_courses',
            name='qusestion1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='django_courses',
            name='qusestion2',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='django_courses',
            name='qusestion3',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='django_courses',
            name='qusestion4',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='java_courses',
            name='ans_op1',
            field=models.CharField(default='false', max_length=100),
        ),
        migrations.AddField(
            model_name='java_courses',
            name='ans_op11',
            field=models.CharField(default='false', max_length=100),
        ),
        migrations.AddField(
            model_name='java_courses',
            name='ans_op2',
            field=models.CharField(default='false', max_length=100),
        ),
        migrations.AddField(
            model_name='java_courses',
            name='ans_op22',
            field=models.CharField(default='false', max_length=100),
        ),
        migrations.AddField(
            model_name='java_courses',
            name='ans_op222',
            field=models.CharField(default='false', max_length=100),
        ),
        migrations.AddField(
            model_name='java_courses',
            name='ans_op2222',
            field=models.CharField(default='false', max_length=100),
        ),
        migrations.AddField(
            model_name='java_courses',
            name='ans_op3',
            field=models.CharField(default='false', max_length=100),
        ),
        migrations.AddField(
            model_name='java_courses',
            name='ans_op33',
            field=models.CharField(default='false', max_length=100),
        ),
        migrations.AddField(
            model_name='java_courses',
            name='ans_op333',
            field=models.CharField(default='false', max_length=100),
        ),
        migrations.AddField(
            model_name='java_courses',
            name='ans_op3333',
            field=models.CharField(default='false', max_length=100),
        ),
        migrations.AddField(
            model_name='java_courses',
            name='ans_op4',
            field=models.CharField(default='false', max_length=100),
        ),
        migrations.AddField(
            model_name='java_courses',
            name='ans_op44',
            field=models.CharField(default='false', max_length=100),
        ),
        migrations.AddField(
            model_name='java_courses',
            name='op1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='java_courses',
            name='op11',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='java_courses',
            name='op2',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='java_courses',
            name='op22',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='java_courses',
            name='op222',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='java_courses',
            name='op2222',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='java_courses',
            name='op3',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='java_courses',
            name='op33',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='java_courses',
            name='op333',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='java_courses',
            name='op3333',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='java_courses',
            name='op4',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='java_courses',
            name='op44',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='java_courses',
            name='qusestion1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='java_courses',
            name='qusestion2',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='java_courses',
            name='qusestion3',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='java_courses',
            name='qusestion4',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='javascript_courses',
            name='ans_op1',
            field=models.CharField(default='false', max_length=100),
        ),
        migrations.AddField(
            model_name='javascript_courses',
            name='ans_op11',
            field=models.CharField(default='false', max_length=100),
        ),
        migrations.AddField(
            model_name='javascript_courses',
            name='ans_op2',
            field=models.CharField(default='false', max_length=100),
        ),
        migrations.AddField(
            model_name='javascript_courses',
            name='ans_op22',
            field=models.CharField(default='false', max_length=100),
        ),
        migrations.AddField(
            model_name='javascript_courses',
            name='ans_op222',
            field=models.CharField(default='false', max_length=100),
        ),
        migrations.AddField(
            model_name='javascript_courses',
            name='ans_op2222',
            field=models.CharField(default='false', max_length=100),
        ),
        migrations.AddField(
            model_name='javascript_courses',
            name='ans_op3',
            field=models.CharField(default='false', max_length=100),
        ),
        migrations.AddField(
            model_name='javascript_courses',
            name='ans_op33',
            field=models.CharField(default='false', max_length=100),
        ),
        migrations.AddField(
            model_name='javascript_courses',
            name='ans_op333',
            field=models.CharField(default='false', max_length=100),
        ),
        migrations.AddField(
            model_name='javascript_courses',
            name='ans_op3333',
            field=models.CharField(default='false', max_length=100),
        ),
        migrations.AddField(
            model_name='javascript_courses',
            name='ans_op4',
            field=models.CharField(default='false', max_length=100),
        ),
        migrations.AddField(
            model_name='javascript_courses',
            name='ans_op44',
            field=models.CharField(default='false', max_length=100),
        ),
        migrations.AddField(
            model_name='javascript_courses',
            name='op1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='javascript_courses',
            name='op11',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='javascript_courses',
            name='op2',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='javascript_courses',
            name='op22',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='javascript_courses',
            name='op222',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='javascript_courses',
            name='op2222',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='javascript_courses',
            name='op3',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='javascript_courses',
            name='op33',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='javascript_courses',
            name='op333',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='javascript_courses',
            name='op3333',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='javascript_courses',
            name='op4',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='javascript_courses',
            name='op44',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='javascript_courses',
            name='qusestion1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='javascript_courses',
            name='qusestion2',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='javascript_courses',
            name='qusestion3',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='javascript_courses',
            name='qusestion4',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='laravel_courses',
            name='ans_op1',
            field=models.CharField(default='false', max_length=100),
        ),
        migrations.AddField(
            model_name='laravel_courses',
            name='ans_op11',
            field=models.CharField(default='false', max_length=100),
        ),
        migrations.AddField(
            model_name='laravel_courses',
            name='ans_op2',
            field=models.CharField(default='false', max_length=100),
        ),
        migrations.AddField(
            model_name='laravel_courses',
            name='ans_op22',
            field=models.CharField(default='false', max_length=100),
        ),
        migrations.AddField(
            model_name='laravel_courses',
            name='ans_op222',
            field=models.CharField(default='false', max_length=100),
        ),
        migrations.AddField(
            model_name='laravel_courses',
            name='ans_op2222',
            field=models.CharField(default='false', max_length=100),
        ),
        migrations.AddField(
            model_name='laravel_courses',
            name='ans_op3',
            field=models.CharField(default='false', max_length=100),
        ),
        migrations.AddField(
            model_name='laravel_courses',
            name='ans_op33',
            field=models.CharField(default='false', max_length=100),
        ),
        migrations.AddField(
            model_name='laravel_courses',
            name='ans_op333',
            field=models.CharField(default='false', max_length=100),
        ),
        migrations.AddField(
            model_name='laravel_courses',
            name='ans_op3333',
            field=models.CharField(default='false', max_length=100),
        ),
        migrations.AddField(
            model_name='laravel_courses',
            name='ans_op4',
            field=models.CharField(default='false', max_length=100),
        ),
        migrations.AddField(
            model_name='laravel_courses',
            name='ans_op44',
            field=models.CharField(default='false', max_length=100),
        ),
        migrations.AddField(
            model_name='laravel_courses',
            name='op1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='laravel_courses',
            name='op11',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='laravel_courses',
            name='op2',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='laravel_courses',
            name='op22',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='laravel_courses',
            name='op222',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='laravel_courses',
            name='op2222',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='laravel_courses',
            name='op3',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='laravel_courses',
            name='op33',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='laravel_courses',
            name='op333',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='laravel_courses',
            name='op3333',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='laravel_courses',
            name='op4',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='laravel_courses',
            name='op44',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='laravel_courses',
            name='qusestion1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='laravel_courses',
            name='qusestion2',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='laravel_courses',
            name='qusestion3',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='laravel_courses',
            name='qusestion4',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='python_courses',
            name='ans_op1',
            field=models.CharField(default='false', max_length=100),
        ),
        migrations.AddField(
            model_name='python_courses',
            name='ans_op11',
            field=models.CharField(default='false', max_length=100),
        ),
        migrations.AddField(
            model_name='python_courses',
            name='ans_op2',
            field=models.CharField(default='false', max_length=100),
        ),
        migrations.AddField(
            model_name='python_courses',
            name='ans_op22',
            field=models.CharField(default='false', max_length=100),
        ),
        migrations.AddField(
            model_name='python_courses',
            name='ans_op222',
            field=models.CharField(default='false', max_length=100),
        ),
        migrations.AddField(
            model_name='python_courses',
            name='ans_op2222',
            field=models.CharField(default='false', max_length=100),
        ),
        migrations.AddField(
            model_name='python_courses',
            name='ans_op3',
            field=models.CharField(default='false', max_length=100),
        ),
        migrations.AddField(
            model_name='python_courses',
            name='ans_op33',
            field=models.CharField(default='false', max_length=100),
        ),
        migrations.AddField(
            model_name='python_courses',
            name='ans_op333',
            field=models.CharField(default='false', max_length=100),
        ),
        migrations.AddField(
            model_name='python_courses',
            name='ans_op3333',
            field=models.CharField(default='false', max_length=100),
        ),
        migrations.AddField(
            model_name='python_courses',
            name='ans_op4',
            field=models.CharField(default='false', max_length=100),
        ),
        migrations.AddField(
            model_name='python_courses',
            name='ans_op44',
            field=models.CharField(default='false', max_length=100),
        ),
        migrations.AddField(
            model_name='python_courses',
            name='op1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='python_courses',
            name='op11',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='python_courses',
            name='op2',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='python_courses',
            name='op22',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='python_courses',
            name='op222',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='python_courses',
            name='op2222',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='python_courses',
            name='op3',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='python_courses',
            name='op33',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='python_courses',
            name='op333',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='python_courses',
            name='op3333',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='python_courses',
            name='op4',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='python_courses',
            name='op44',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='python_courses',
            name='qusestion1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='python_courses',
            name='qusestion2',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='python_courses',
            name='qusestion3',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='python_courses',
            name='qusestion4',
            field=models.CharField(default='', max_length=100),
        ),
    ]
