# Generated by Django 2.2.3 on 2019-09-09 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20190909_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='java_courses',
            name='ans_op2',
            field=models.CharField(default='true', max_length=100),
        ),
    ]
