# Generated by Django 2.2.3 on 2019-09-10 04:48

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_auto_20190909_2217'),
    ]

    operations = [
        migrations.CreateModel(
            name='Java_quize_courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(default='python', max_length=100)),
                ('content', tinymce.models.HTMLField()),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('question1', models.CharField(default='', max_length=100)),
                ('op1', models.CharField(default='', max_length=100)),
                ('op11', models.CharField(default='', max_length=100)),
                ('ans1', models.CharField(default='false', max_length=100)),
                ('ans11', models.CharField(default='false', max_length=100)),
                ('question2', models.CharField(default='', max_length=100)),
                ('op2', models.CharField(default='', max_length=100)),
                ('op22', models.CharField(default='', max_length=100)),
                ('op222', models.CharField(default='', max_length=100)),
                ('op2222', models.CharField(default='', max_length=100)),
                ('ans2', models.CharField(default='false', max_length=100)),
                ('ans22', models.CharField(default='false', max_length=100)),
                ('ans222', models.CharField(default='false', max_length=100)),
                ('ans2222', models.CharField(default='false', max_length=100)),
                ('question3', models.CharField(default='', max_length=100)),
                ('op3', models.CharField(default='', max_length=100)),
                ('op33', models.CharField(default='', max_length=100)),
                ('op333', models.CharField(default='', max_length=100)),
                ('op3333', models.CharField(default='', max_length=100)),
                ('ans3', models.CharField(default='false', max_length=100)),
                ('ans33', models.CharField(default='false', max_length=100)),
                ('ans333', models.CharField(default='false', max_length=100)),
                ('ans3333', models.CharField(default='false', max_length=100)),
                ('question4', models.CharField(default='', max_length=100)),
                ('op4', models.CharField(default='', max_length=100)),
                ('op44', models.CharField(default='', max_length=100)),
                ('ans4', models.CharField(default='false', max_length=100)),
                ('ans44', models.CharField(default='false', max_length=100)),
                ('question5', models.CharField(default='', max_length=100)),
                ('op5', models.CharField(default='', max_length=100)),
                ('op55', models.CharField(default='', max_length=100)),
                ('op555', models.CharField(default='', max_length=100)),
                ('op5555', models.CharField(default='', max_length=100)),
                ('ans5', models.CharField(default='false', max_length=100)),
                ('ans55', models.CharField(default='false', max_length=100)),
                ('ans555', models.CharField(default='false', max_length=100)),
                ('ans5555', models.CharField(default='false', max_length=100)),
            ],
        ),
    ]
