# Generated by Django 2.2.3 on 2019-09-10 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_java_quize_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='java_quize_courses',
            name='content',
        ),
    ]
