# Generated by Django 2.2.3 on 2019-09-10 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_auto_20190910_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='java_quize_courses',
            name='ans1',
            field=models.CharField(blank=True, default='false', max_length=100),
        ),
        migrations.AlterField(
            model_name='java_quize_courses',
            name='ans11',
            field=models.CharField(blank=True, default='false', max_length=100),
        ),
        migrations.AlterField(
            model_name='java_quize_courses',
            name='ans2',
            field=models.CharField(blank=True, default='false', max_length=100),
        ),
        migrations.AlterField(
            model_name='java_quize_courses',
            name='ans22',
            field=models.CharField(blank=True, default='false', max_length=100),
        ),
        migrations.AlterField(
            model_name='java_quize_courses',
            name='ans222',
            field=models.CharField(blank=True, default='false', max_length=100),
        ),
        migrations.AlterField(
            model_name='java_quize_courses',
            name='ans2222',
            field=models.CharField(blank=True, default='false', max_length=100),
        ),
        migrations.AlterField(
            model_name='java_quize_courses',
            name='ans3',
            field=models.CharField(blank=True, default='false', max_length=100),
        ),
        migrations.AlterField(
            model_name='java_quize_courses',
            name='ans33',
            field=models.CharField(blank=True, default='false', max_length=100),
        ),
        migrations.AlterField(
            model_name='java_quize_courses',
            name='ans333',
            field=models.CharField(blank=True, default='false', max_length=100),
        ),
        migrations.AlterField(
            model_name='java_quize_courses',
            name='ans3333',
            field=models.CharField(blank=True, default='false', max_length=100),
        ),
        migrations.AlterField(
            model_name='java_quize_courses',
            name='ans4',
            field=models.CharField(blank=True, default='false', max_length=100),
        ),
        migrations.AlterField(
            model_name='java_quize_courses',
            name='ans44',
            field=models.CharField(blank=True, default='false', max_length=100),
        ),
        migrations.AlterField(
            model_name='java_quize_courses',
            name='ans5',
            field=models.CharField(blank=True, default='false', max_length=100),
        ),
        migrations.AlterField(
            model_name='java_quize_courses',
            name='ans55',
            field=models.CharField(blank=True, default='false', max_length=100),
        ),
        migrations.AlterField(
            model_name='java_quize_courses',
            name='ans555',
            field=models.CharField(blank=True, default='false', max_length=100),
        ),
        migrations.AlterField(
            model_name='java_quize_courses',
            name='ans5555',
            field=models.CharField(blank=True, default='false', max_length=100),
        ),
    ]
