# Generated by Django 2.2.3 on 2019-09-14 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_auto_20190914_2102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses_name',
            name='pub',
        ),
    ]
