# Generated by Django 2.2.3 on 2019-09-14 15:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_remove_courses_name_pub'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses_name',
            name='pub',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2019, 9, 14, 15, 4, 1, 271978, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
