# Generated by Django 2.2.3 on 2019-09-15 05:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0021_remove_courses_name_pub'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses_name',
            name='dateTime',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2019, 9, 15, 5, 38, 55, 188912, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
