# Generated by Django 2.2.3 on 2019-09-15 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0023_auto_20190915_1855'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Courses_name',
        ),
    ]
