# Generated by Django 2.2.3 on 2019-09-15 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0024_delete_courses_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses_name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('pic', models.ImageField(upload_to='images/')),
                ('details', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Courses_namee',
        ),
    ]
