# Generated by Django 2.2.3 on 2019-09-17 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0026_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='message',
            new_name='messages',
        ),
    ]
