# Generated by Django 2.2.3 on 2019-09-17 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0027_auto_20190917_2051'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='messages',
            new_name='message',
        ),
    ]
