# Generated by Django 2.2.3 on 2019-09-25 12:01

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0031_bootstrap_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='java_courses',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
