# Generated by Django 2.2.3 on 2019-09-25 12:04

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0032_auto_20190925_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='java_courses',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
