# Generated by Django 2.2.3 on 2019-09-25 12:07

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0033_auto_20190925_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='java_courses',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
    ]
